### ISSUE TITLE
Compilation of emqx_plugin_template plugin with EMQX fails

### ISSUE THREAD

**Issue by sushantAtAws** [emqx/emqx-plugin-template#101]
Hi, 

I am following the documentation to compile emqx with the template plugin:

```
export EMQX_EXTRA_PLUGINS=emqx_plugin_template
make
```
Output/Error:
```
===> Verifying dependencies...
===> Fetching emqx_plugin_template (from {git,"https://github.com/emqx/emqx-plugin-template",
                                {tag,"4.3.0"}})
===> Compiling emqx_plugin_template
===> Compiling _build/default/lib/emqx_plugin_template/src/emqx_plugin_template.erl failed
emqx_plugin_template.erl:19: can't find include file "emqx.hrl"

emqx_plugin_template.erl:145: record message undefined
emqx_plugin_template.erl:152: record message undefined

make: *** [Makefile:78: emqx] Error 1                                
```

PS. I know this is community supported but I am an erlang newbie to contribute a fix here.

**Comment by zmstone** [comment]
Hi. @sushantAtAws 
Sorry this issue has fallen between the chairs.
The issue was created in July, I assume you were following emqx.git's master branch ?
The guide is for 4.3 which is in `main-v4.3` branch.

`master` branch is the dev branch for 5.0 release which has a brand new way of plugin build & integration process.
but back in July, the new way was not started, and the old way was broken on the master branch.
